[tool.black]
line-length = 120
include = '¥.pyi?$'
skip-string-normalization = true

[tool.isort]
line_length = 120
force_grid_wrap = 0
include_trailing_comma = true
multi_line_output = 3
use_parentheses = true
